name: Build-and-publish-docker-images-workflow

on:
  push

jobs:
  Build-and-publish-docker-images:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.body, 'The workflow build-and-publish-docker-images was intentionally skipped.') == false
    steps:
      - uses: actions/checkout@master

      - name: Build and publish AasxServerBlazor
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adminshellio/aasx-server-blazor-for-demo
          tag_with_ref: true
          dockerfile: src/docker/Dockerfile-AasxServerBlazor

      - name: Build and publish AasxServerCore
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adminshellio/aasx-server-core-for-demo
          tag_with_ref: true
          dockerfile: src/docker/Dockerfile-AasxServerCore

  multi:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.body, 'The workflow build-and-publish-docker-images was intentionally skipped.') == false
    steps:
      - uses: actions/checkout@master
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          outputs: adminshellio/aasx-server-blazor-for-demo-multi
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: src/docker/Dockerfile-AasxServerBlazor
